//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tru.Repo.Test.Repos.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerRepoScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerRepoScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tru.Repo.Test.Repos.CustomerRepo.CustomerRepoScript", typeof(CustomerRepoScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE TruTest.Customer WHERE Email = @Email.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TruTest.Customer WHERE Email = @Email.
        /// </summary>
        internal static string GetWithEmail {
            get {
                return ResourceManager.GetString("GetWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TruTest.Customer WHERE FirstName = @FirstName.
        /// </summary>
        internal static string GetWithFirstName {
            get {
                return ResourceManager.GetString("GetWithFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TruTest.Customer WHERE LastName = @LastName.
        /// </summary>
        internal static string GetWithLastName {
            get {
                return ResourceManager.GetString("GetWithLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE TruTest.Customer
        ///(
        ///	Email NVARCHAR(100) NOT NULL,
        ///	FirstName NVARCHAR(100) NOT NULL,
        ///	LastName NVARCHAR(100) NOT NULL,
        ///	CONSTRAINT PK_TruTest_Customer_Email PRIMARY KEY CLUSTERED (Email)
        ///)
        ///
        ///CREATE NONCLUSTERED INDEX IDX_TruTest_Customer_FirstName ON TruTest.Customer (FirstName)
        ///CREATE NONCLUSTERED INDEX IDX_TruTest_Customer_LastName ON TruTest.Customer (LastName).
        /// </summary>
        internal static string Patch0 {
            get {
                return ResourceManager.GetString("Patch0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT * FROM TruTest.Customer WHERE Email = @Email)
        ///BEGIN
        ///	UPDATE TruTest.Customer SET FirstName = @FirstName, LastName = @LastName WHERE Email = @Email
        ///END
        ///ELSE
        ///BEGIN
        ///	INSERT INTO TruTest.Customer VALUES(@Email, @FirstName, @LastName)
        ///END.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
